#!/usr/bin/env bash
#
# Update the routes on the server

echo 'Handling git...'
git add config/routes.rb
git commit -m "Updating server-side routes"
git push

echo 'Updating server...'
ssh nohm@nohm.eu "cd /var/www/badger/ && git pull && rake routes && touch tmp/restart.txt"
