#!/usr/bin/env bash
#
# Send new gems to the server

echo 'Handling git...'
git add Gemfile Gemfile.lock
git commit -m "Updating server-side gems"
git push

echo 'Updating server...'
ssh nohm@nohm.eu "cd /var/www/badger/ && git pull && bundle update && gem clean && bundle exec rake assets:precompile RAILS_ENV=production && rake assets:clean && touch tmp/restart.txt"
